<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /var/www/vine/CustomExtensions/namelessevents/xml/schema/CRM/Namelessevents/namelesseventsProfiles.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d6c14f78477c4364431933a8bfa00fb0)
 */

/**
 * Database access object for the NamelesseventsProfiles entity.
 */
class CRM_Namelessevents_DAO_NamelesseventsProfiles extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_namelessevents_profiles';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique NamelesseventsProfiles ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int
   */
  public $event_id;

  /**
   * Per-event profile-per-sub-type settings
   *
   * @var string
   */
  public $settings;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_namelessevents_profiles';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Namelessevents_ExtensionUtil::ts('Unique NamelesseventsProfiles ID'),
          'required' => TRUE,
          'where' => 'civicrm_namelessevents_profiles.id',
          'table_name' => 'civicrm_namelessevents_profiles',
          'entity' => 'NamelesseventsProfiles',
          'bao' => 'CRM_Namelessevents_DAO_NamelesseventsProfiles',
          'localizable' => 0,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Namelessevents_ExtensionUtil::ts('FK to Event'),
          'where' => 'civicrm_namelessevents_profiles.event_id',
          'table_name' => 'civicrm_namelessevents_profiles',
          'entity' => 'NamelesseventsProfiles',
          'bao' => 'CRM_Namelessevents_DAO_NamelesseventsProfiles',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Event',
        ],
        'settings' => [
          'name' => 'settings',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Namelessevents_ExtensionUtil::ts('Per-event profile-per-sub-type settings'),
          'description' => CRM_Namelessevents_ExtensionUtil::ts('Per-event profile-per-sub-type settings'),
          'required' => FALSE,
          'maxlength' => 1000,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_namelessevents_profiles.settings',
          'export' => TRUE,
          'table_name' => 'civicrm_namelessevents_profiles',
          'entity' => 'NamelesseventsProfiles',
          'bao' => 'CRM_Namelessevents_DAO_NamelesseventsProfiles',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'namelessevents_profiles', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'namelessevents_profiles', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
